firstline: XPKeeper
firstline_colour: &0
must_use_fist: true
withdraw: 5
set_limits: false
limits:
  - 30
  - 50
  - 100
# messages must contain %s and %d where appropriate as these are placeholders that get replaced in the message!
messages:
  have_sign: You already have an XPKeeper in this world!
  no_perms_create: You do not have permission to make an XPKeeper sign!
  no_perms_command: You do not have permission to use that command!
  arguments: Not enough command arguments!
  no_player: Could not find that player!
  removed: The XPKeeper was successfully removed.
  use_fist: You must hit the sign with your fist.
  deposit: You deposited %d XP and have reached level %d :)
  withdraw_all: You withdrew all your XP!
  withdraw_some: You withdrew %d XP Levels!
  not_your_sign: Get your own sign!
  click_sign: Click the XPKeeper sign you wish to remove.
  no_sign: Couldn't find the sign, maybe you're too far away.
  look_sign: You aren't looking at a sign!
  not_enough: You don't have enough XP! Try withdrawing from your XPKeeper sign first.
  giver: 'You payed %s %d XP :)'
  reciever: '%s payed you %d XP :)'
  use_command: Please use the /xpkremove command to delete an XPKeeper sign!
  no_grief: Stop trying to grief this XPKeeper sign!